name: softcore
description: flutter project clean core arch.
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animation_wrappers: ^3.0.0
  platform: ^3.0.0  # Add the latest compatible version here
  built_value: ^8.8.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  flutter_svg: ^2.0.9
  get: ^4.6.5
  injectable: ^2.3.2
  intl: ^0.18.0
  rxdart: ^0.28.0
  get_it: ^7.5.0  # Use the latest version available on pub.dev

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.16.0



# URLs pointing to your package's homepage and repository
homepage: https://github.com/Prog-MohamedAbdelnaser/flutterCleanArchitecture-core.git
repository: https://github.com/Prog-MohamedAbdelnaser/flutterCleanArchitecture-core.git

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true