library softMaterials;

export 'src/core/extensions/extensions.dart';
export 'src/core/components/material_stateless_widget.dart';
export 'src/core/components/material_widget_bloc.dart';
export 'src/core/managers/dialogs_manager.dart';
export 'src/core/components/placeholder/error_placeholder_widget.dart';
export 'src/core/components/loading_widget.dart';
export 'src/core/components/restart_app_widget.dart';
export 'src/core/components/buttons/app_cupertino_button.dart';
export 'src/core/components/buttons/app_icon.dart';
export 'src/core/components/buttons/outlint_button.dart';
export 'src/core/components/bottom_navigation_widget.dart';
export 'src/core/components/buttons/options_menu_button.dart';
export 'src/core/components/buttons/app_icon_button.dart';
export 'src/core/components/text_field/material_text_field.dart';
export 'src/core/components/texts/material_text.dart';
export 'src/core/components/texts/row_rich_texts.dart';
export 'src/core/components/helper/helper_widgets.dart' ;
export 'src/core/components/helper/image_builder.dart' ;
export 'src/core/components/drop_down/drop_down2.dart';
export 'src/core/components/bottom_sheet/common_list_item.dart';
export 'src/core/components/stream/stream_data_state_widget.dart';
export 'src/core/components/stream/stream_state_widget.dart';
export 'src/core/bloc/data_state.dart';

export 'basebloc.dart';
export 'errorManager.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'package:softcore/src/core/resources/validation.dart';
